project_id = "wuihldjxymgjpxcyorxj"

[functions.auth-login]
verify_jwt = false

[functions.auth-change-password]
verify_jwt = false

[functions.auth-verify]
verify_jwt = false

[functions.auth-seed]
verify_jwt = false