// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuihldjxymgjpxcyorxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1aWhsZGp4eW1nanB4Y3lvcnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Nzc2MTUsImV4cCI6MjA3MTI1MzYxNX0.9j-nAjT0rKzKG7AjtcdR6zqwDHh3gtf_9CHpqFC2o_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});